########################################## Identify Bit information of APMSSO installed ############################
- shell: "file {{ NETE_PS_ROOT }}/lib/libIntroscopeNativeDataAPI.so"
  register: ASSO_BIT_INFO
- set_fact:
     ASSO_BIT: "64"
  when: "'64-bit' in ASSO_BIT_INFO.stdout"
- set_fact:
     ASSO_BIT: "32"
  when: "'32-bit' in ASSO_BIT_INFO.stdout"
##################################################################################################################
########################## Stoping policy server ########################################################
- command: ./stop-all
  args:
    chdir: "{{ NETE_PS_ROOT }}"
  register: policy_server_stop
  failed_when: false

###############################################################################################################
########################## Block for rollback  configuration of APMSSO Agent on Remote machine ##################
- block:
    - copy:
        src: "{{ apmsso_install }}/{{ CA_APM_SSO_DIRECTORY }}/backup/siteminder/lib{{ ASSO_BIT }}/{{ item }}"
        dest: "{{ NETE_PS_ROOT }}/lib/"
        remote_src: yes
      failed_when: false
      with_items:
          - libIntroscopeNativeDataAPI.so
          - libxerces-c-3.1.so
          - libapr-1.so.0
          - libboost_regex-mt.so.5
          - libicudata.so.42
          - libicuuc.so.42
          - libicui18n.so.42

    - copy:
        src: "{{ apmsso_install }}/{{ CA_APM_SSO_DIRECTORY }}/backup/siteminder/config{{ ASSO_BIT }}/{{ item }}"
        dest: "{{ NETE_PS_ROOT }}/config/"
        remote_src: yes
      failed_when: false
      with_items:
          - IntroscopeCAPIConfig.xml
          - SiteMinderPSdefs.xml
    - command: "./start-all"
      args:
        chdir: "{{ NETE_PS_ROOT }}"
      register: policy_server_start
      failed_when: false
    - set_fact:
         report_output: {"stdout":"APM SSO Rolled back to previous version."}
#######################################################################################################
###################################### print report if facing problem to stop policy server ###################
#- block:
#    - template:
#         src: "{{ playbook_dir }}/roles/apmsso_role/template/report.j2"
#         dest: "{{ playbook_dir }}/report.log"
#      delegate_to: localhost
