- name: Restart IIS service
  win_service:
    name: Iisadmin
    state: restarted
  register: iis_restart


- set_fact:
     report: {"stdout": "IIS service restarted"}

- name: Block for Report
  block:
    - template:
         src: "{{ playbook_dir }}/roles/dotnet/templates/report.j2"
         dest: "{{ playbook_dir }}/report.log"
      delegate_to: localhost

