- name: Restart IIS service
  win_service:
    name: Iisadmin
    state: stopped
  register: iis_stop
  
##########################################################################
- set_fact:
     report: {"stdout": "IIS service is stopped"}
  when: iis_stop.state == "stopped"
- set_fact:
     report: {"stdout":"IIS service could not stopped, please check manually"}
  when: iis_stop.state != "stopped"
###############################################################################
- name: Block for Report
  block:
    - template:
         src: "{{ playbook_dir }}/roles/dotnet/templates/report.j2"
         dest: "{{ playbook_dir }}/report.log"
      delegate_to: localhost
#################################################################################

